sudo gedit /etc/apt/sources.list 

deb http://mirrors.ustc.edu.cn/ubuntu/ xenial main restricted universe multiverse
deb http://mirrors.ustc.edu.cn/ubuntu/ xenial-security main restricted universe multiverse
deb http://mirrors.ustc.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
deb http://mirrors.ustc.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse
deb http://mirrors.ustc.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial-security main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse
deb-src http://mirrors.ustc.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse

sudo apt-get update
sudo apt-get remove libappstream3
sudo apt-get update
sudo apt-get install golang python3-dev python-dev libcupti-dev libjpeg-turbo8-dev make tmux htop chromium-browser git cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig

anaconda
wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
bash Anaconda3-4.2.0-Linux-x86_64.sh
export PATH="/home/$USER/anaconda3/bin:$PATH"
source ~/.bashrc
conda create --name universe python=3.5 anaconda
source activate universe
conda install pip six libgcc swig
conda install opencv
cd ~
git clone https://github.com/openai/gym.git
cd ~/gym
pip install -e .
pip uninstall gym
sudo pip install gym==0.9.5
sudo pip install gym[atari]

sudo vi  .bashrc
添加
alias sudo='sudo env PATH=$PATH'
之后
source ~/.bashrc

cd ~
git clone https://github.com/openai/universe.git
cd universe
pip install -e .

docker
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce
sudo service docker start


error:
[2018-10-13 16:59:49,386] VNC server localhost:5900 did not come up yet (error: [Errno 111] Connection refused). Sleeping for 1s.
Traceback (most recent call last):
  File "test-universe.py", line 5, in <module>
    env.configure(remotes=1)  # automatically creates a local docker container
  File "/home/zengxiaohui/universe/universe/wrappers/timer.py", line 14, in configure
    self.env.configure(**kwargs)
  File "/home/zengxiaohui/universe/universe/wrappers/render.py", line 21, in configure
    self.env.configure(**kwargs)
  File "/home/zengxiaohui/universe/universe/wrappers/throttle.py", line 32, in configure
    self.env.configure(**kwargs)
  File "/home/zengxiaohui/universe/universe/envs/vnc_env.py", line 199, in configure
    use_recorder_ports=record,
  File "/home/zengxiaohui/universe/universe/remotes/build.py", line 19, in build
    n=n,
  File "/home/zengxiaohui/universe/universe/remotes/docker_remote.py", line 55, in __init__
    self._start()
  File "/home/zengxiaohui/universe/universe/remotes/docker_remote.py", line 85, in _start
    self.healthcheck(self.instances)
  File "/home/zengxiaohui/universe/universe/remotes/docker_remote.py", line 110, in healthcheck
    start_timeout=30,
  File "/home/zengxiaohui/universe/universe/remotes/healthcheck.py", line 14, in run
    healthcheck.run()
  File "/home/zengxiaohui/universe/universe/remotes/healthcheck.py", line 131, in run
    self._register_vnc(address)
  File "/home/zengxiaohui/universe/universe/remotes/healthcheck.py", line 63, in _register_vnc
    raise error.Error('VNC server {} did not come up within {}s'.format(address, self.start_timeout))
universe.error.Error: VNC server localhost:5900 did not come up within 30s
[2018-10-13 16:59:50,780] Killing and removing container: id=e87558cb7c9565de75c6189a0f313fdb47a92d0c8324e3905599a633f514a8d0
解决：
cd openai-flashgames-patch
sudo bash build.sh

error:
universe-twEjpw-0 | [tigervnc]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
2018/10/20 16:10:02 I1020 16:10:02.200642 3772 gymvnc.go:550] [0:localhost:5900] connection established
libGL error: unable to load driver: vmwgfx_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: vmwgfx
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Traceback (most recent call last):
universe-twEjpw-0 | [tigervnc]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
  File "test-universe.py", line 11, in <module>
    env.render()
  File "/home/zengxiaohui/anaconda3/envs/universe/lib/python3.5/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/zengxiaohui/anaconda3/envs/universe/lib/python3.5/site-packages/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/home/zengxiaohui/anaconda3/envs/universe/lib/python3.5/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/zengxiaohui/universe/universe/wrappers/render.py", line 52, in _render
    return self.env.render(mode=mode, *args, **kwargs)
  File "/home/zengxiaohui/anaconda3/envs/universe/lib/python3.5/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/zengxiaohui/anaconda3/envs/universe/lib/python3.5/site-packages/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/home/zengxiaohui/anaconda3/envs/universe/lib/python3.5/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/zengxiaohui/universe/universe/envs/vnc_env.py", line 552, in _render
    self.vnc_session.render(self.connection_names[0])
go_vncdriver.Error: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
/home/zengxiaohui/software/go-vncdriver/.build/src/github.com/openai/go-vncdriver/vncgl/vncgl.go:60: couldn't create window
/home/zengxiaohui/software/go-vncdriver/.build/src/github.com/openai/go-vncdriver/gymvnc/gymvnc.go:245: could not render
[2018-10-20 16:10:02,322] Killing and removing container: id=9edbc88c7bd4127bc832abb26afb646a3dc91e828c30eca7618ea34a76c0add4
解决：
sudo apt-get install libgl1-mesa-dri libgl1-mesa-dri:i386